### PR TITLE
DDF-1264 updated text_ws in schema.xml type descriptor to use for wildcard searching

### PR DESCRIPTION
**Pull request by wmcnalli**
@kcwire
@millerw8
@pklinef
@wmcnalli
@jlcsmith
@beyelerb
@emanns95
@jrnorth
@coyotesqrl

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/67)

### CODE REVIEW

**Comment by kcwire** [comment]
+1

**Comment by coyotesqrl** [comment]
+1

**Comment by coyotesqrl** [comment]
Pulled; built; tested. Verified.

**Comment by pklinef** [comment]
:+1:

**Comment by emanns95** [comment]
+1

**Comment by jrnorth** [comment]
LGTM

**Pull request merged**
