### PR TITLE
DDF-747 added security admin module

### PR DESCRIPTION
**Pull request by stustison**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/36)

### CODE REVIEW

**Comment by shaundmorris** [comment]
<sup>**[security/security-admin-module/src/main/webapp/css/index.css, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-JngRtWI9SoD01w1qQ4k)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/src/main/webapp/css/index.css#L0)):</sup>
So does this file just need to exist for testing purposes? Just was verifying it was necessary and okay to be empty.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Comment by shaundmorris** [comment]
I am not sure what is going on with the Travis build, but this built fine for me. 

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Comment by shaundmorris** [comment]
Reviewed files:
- security-services-app/src/main/resources/features.xml @ r1
- security/pom.xml @ r1
- security/security-admin-module/.bowerrc @ r1
- security/security-admin-module/bower.json @ r1
- security/security-admin-module/Gruntfile.js @ r1
- security/security-admin-module/package.json @ r1
- security/security-admin-module/pom.xml @ r1
- security/security-admin-module/server-impl.js @ r1
- security/security-admin-module/server.js @ r1
- security/security-admin-module/src/main/grunt/tasks/bower.js @ r1
- security/security-admin-module/src/main/java/org/codice/ddf/security/admin/module/SecurityModulePlugin.java @ r1
- security/security-admin-module/src/main/resources/OSGI-INF/blueprint/blueprint.xml @ r1
- security/security-admin-module/src/main/webapp/css/index.css @ r1
- security/security-admin-module/src/main/webapp/index.html @ r1
- security/security-admin-module/src/main/webapp/js/application.js @ r1
- security/security-admin-module/src/main/webapp/js/module.js @ r1
- security/security-admin-module/src/main/webapp/main.js @ r1
- security/security-admin-module/src/main/webapp/WEB-INF/web.xml @ r1
- security/security-admin-module/test.js @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Comment by stustison** [comment]
<sup>**[security/security-admin-module/src/main/webapp/css/index.css, line 0 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-JngRtWI9SoD01w1qQ4k)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/src/main/webapp/css/index.css#L0)):</sup>
It doesn't need to exist but it will as soon as we start doing content into this app. I was just creating it ahead of time 

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Comment by shaundmorris** [comment]
<sup>**[security/security-admin-module/pom.xml, line 46 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-Jo2ZHXGcoGeFOwH2CeC)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/pom.xml#L46)):</sup>
Can you update the frontend-maven-plugin verison  to 0.0.23 like in this https://github.com/codice/ddf-platform/pull/40? Ultimately I agree with @pklinef we probably should use plugin-management for this if we can.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Comment by pklinef** [comment]
<sup>**[security/security-admin-module/bower.json, line 17 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-Jo5l6m-QKad11yXlHC7)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/bower.json#L17)):</sup>
There is a way to use a newer version of lodash with backbone.  Take a look at this PR for an example.

https://github.com/codice/ddf-ui/pull/68/commits

---

<sup>**[security/security-admin-module/pom.xml, line 46 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-Jo2ZHXGcoGeFOwH2CeC)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/pom.xml#L46)):</sup>
:+1: 

---

<sup>**[security/security-admin-module/pom.xml, line 106 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-Jo5lW2_euQdecy0tE2i)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/pom.xml#L106)):</sup>
If we do not plan to make an AsciiDoctor help page for this module, then I saw remove this.

---

<sup>**[security/security-admin-module/src/main/grunt/tasks/bower.js, line 2 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/36#-Jo5lksYkDH2zFE8OX8c)** ([raw file](https://github.com/codice/ddf-platform/blob/986a5f3c80d9a1cca9876af59770914024cc71bb/security/security-admin-module/src/main/grunt/tasks/bower.js#L2)):</sup>
We keep reusing this.  We should consider pulling this out into another repo at some point.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/36)

**Pull request merged**
