### PR TITLE
DDF-1318: Fixed CSW Source creation

### PR DESCRIPTION
**Pull request by AzGoalie**
This is the same pull request as https://github.com/codice/ddf-admin/pull/92 but moving here because of repository merges.

@brendan-hofmann
@brianfelix
@kguerriero
@shaundmorris

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/81)

### CODE REVIEW

**Comment by brendan-hofmann** [comment]
:+1:

**Comment by shaundmorris** [comment]
Verified build and CSW creation in the sources module. Other reviewers have approved on previous PR. :+1:

**Comment by brianfelix** [comment]
:+1:

**Comment by kguerriero** [comment]
looks good :+1:

**Pull request merged**
