### PR TITLE
DDF-1194 Adding a utility class for exceptions

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- Added a utility class for exceptions
  - Added method to get the full messsage of a throwable by tracing back through the causes.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/46)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@ricklarsen @figliold

**Comment by andrew-fiedler** [comment]
@brendan-hofmann

**Comment by figliold** [comment]
:+1: 

---

Review status: 0 of 1 files reviewed, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/46)

**Comment by brendan-hofmann** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks broke.

---

<sup>**[util/src/main/java/org/codice/ddf/platform/util/Exceptions.java, line 30 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/46#-JpmBWTKv-vsM9v0Qj2A)** ([raw file](https://github.com/codice/ddf-platform/blob/23e5e76cf7469fb4c019f4966d8d0c2f68c018e2/util/src/main/java/org/codice/ddf/platform/util/Exceptions.java#L30)):</sup>
Could be more descriptive on these. The param should indicate it's meant for nested exceptions, and the return should explain how it unwinds in reverse order.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/46)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks broke.
Reviewed files:
- util/src/main/java/org/codice/ddf/platform/util/Exceptions.java @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/46)

**Pull request merged**
