### PR TITLE
DDF-1239 Updating metric retrieval to account for rrd4j quirkyness

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- pom.xml:  Bumped the version of rrd4j to the latest.
 - RrdMetricsRetriever.java:
  - Updated the getMetricData method to only include data within the time range specified.  Changed from private to public.
 - RrdDumper.java:  Deleted.  I did a thorough search, and this wasn't used anywhere.
 - RrdMetricsRetrieverTest.java:
  - Added an RrdFileBuilder, then updated all the test cases to use it.  It handles a lot of the boilerplate code I was seeing, and makes sure to close out the RrdDb for each one (so I removed that from the tearDown method).  Using the builder will help us easily construct whatever file we need for each test.
  - Added a test "testGetMetricDataTimeRangeFiltering" to verify that metric data is returned within the specified time range.
  - Moved things common things like start time and rrdstep to be static final variables.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/55)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@tbatieConnexta @wmcnalli

**Comment by brendan-hofmann** [comment]
Review status: 3 of 4 files reviewed, 3 unresolved discussions, some commit checks broke.
Reviewed files:
- metrics/platform-metrics-reporting/pom.xml @ r1
- metrics/platform-metrics-reporting/src/main/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetriever.java @ r1
- metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdDumper.java @ r1

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 513 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8g_lI1mO7y7-g_BD)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L513)):</sup>
Wouldn't this value normally be a function of step size and date range? Something like (start-end)/step=numSamples ?

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 563 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8AkrJWKqc_WLXjwr)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L563)):</sup>
What does this logic do, exactly? Shouldn't the step size and number of steps relate to the length of the record somehow?

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 680 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8PBIFKYeNLQf2FRj)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L680)):</sup>
Boo, commented out code. Should be deleted.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by andrew-fiedler** [comment]
Review status: 3 of 4 files reviewed, 3 unresolved discussions, some commit checks broke.

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 513 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8g_lI1mO7y7-g_BD)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L513)):</sup>
We could do it that way, but all of the test cases wanted to give a start time and number of samples (with endtime derived from that).  My new test case was the only one that cared about endtime.

endtime = starttime + step*numSamples

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 563 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8AkrJWKqc_WLXjwr)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L563)):</sup>
I'm not entirely sure what it does.  I had trouble understanding the documentation from rrd. 

http://rrd4j.googlecode.com/svn/trunk/javadoc/reference/org/rrd4j/core/RrdDef.html#addArchive(org.rrd4j.ConsolFun, double, int, int)

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 680 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8PBIFKYeNLQf2FRj)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L680)):</sup>
I actually wanted to know if we could get rid of this method entirely.  Is anyone using it for anything?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by brendan-hofmann** [comment]
Review status: 3 of 4 files reviewed, 3 unresolved discussions, some commit checks broke.

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 513 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8g_lI1mO7y7-g_BD)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L513)):</sup>
Ah, I see how you're using it now, that also makes sense.

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 563 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8AkrJWKqc_WLXjwr)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L563)):</sup>
The rrdtool documentation isn't much better. I guess I'll just assume it works. :/

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 680 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8PBIFKYeNLQf2FRj)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L680)):</sup>
I'm guessing someone used it to debug rrd files via the logger once upon a time. I suppose it doesn't hurt to leave it in, but you should definitely fix or remove the commented out code.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by brendan-hofmann** [comment]
Built, tested, installed, ran, lgtm.

---

Review status: all files reviewed, 3 unresolved discussions, some commit checks broke.
Reviewed files:
- metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by andrew-fiedler** [comment]
Review status: 3 of 4 files reviewed, 3 unresolved discussions, some commit checks pending.

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 563 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8AkrJWKqc_WLXjwr)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L563)):</sup>
From what I can tell, you're probably going to want to set numRows to the numSamples you want.  Otherwise it does some strange stuff.  Took me a while to figure out why I wasn't getting any metric data even though I gave it plenty of samples.  

---

<sup>**[metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java, line 680 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/55#-JrZ8PBIFKYeNLQf2FRj)** ([raw file](https://github.com/codice/ddf-platform/blob/275d51e7710836739a48b663f43c22aba9fee5c5/metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java#L680)):</sup>
I uncommented it, tested it and it worked.  I decided to hide the running of dumpData behind a flag though.  If a developer wants to look at the logs, it'll be easy enough to flip it on.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by brendan-hofmann** [comment]
Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- metrics/platform-metrics-reporting/src/test/java/ddf/metrics/reporting/internal/rrd4j/RrdMetricsRetrieverTest.java @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Comment by stustison** [comment]
looks good

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/55)

**Pull request merged**
