### PR TITLE
DDF 1322 Merge ddf-admin into ddf-platform

### PR DESCRIPTION
**Pull request by jckilmer**
@pklinef @rzwiefel @roelens8

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/77)

### CODE REVIEW

**Comment by pklinef** [comment]
Remove the extra hidden files from the new admin folder that used to be needed when it was its own repo.

**Comment by jckilmer** [comment]
@pklinef I removed .gitattributes, .gitignore, .travis.yml, as well as LICENSE.md and README.md in this commit: https://github.com/jckilmer/ddf-platform/commit/1fcfb8cc609d824fcf1467e6fd2046d09c145fb0, are there other files that need to be removed?

**Comment by coyotesqrl** [comment]
Pulled, built, tested. The only issue was external to this and is addressed in [this PR against ddf](https://github.com/codice/ddf/pull/69).

This is good to go to the best of my ability to test.

**Comment by roelens8** [comment]
Reviewed 307 of 307 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/77)

**Pull request merged**
