### PR TITLE
DDF-1223 fixed the security assertion store so that it creates security tokens with a created and expires date

### PR DESCRIPTION
**Pull request by stustison**
@shaundmorris @mverret @clockard

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/54)

### CODE REVIEW

**Comment by clockard** [comment]
+1 Looks good.

**Comment by shaundmorris** [comment]
The current plan is to address this with integration testing (itests)

**Comment by shaundmorris** [comment]
:+1: Built fine for me. I like the null checks on the samlAssertionWrapper.

**Comment by mverret** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks broke.

---

<sup>**[security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java, line 95 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-platform/54#-JqkSh4LfthpvEDmGWgN)** ([raw file](https://github.com/codice/ddf-platform/blob/80a12ee27b936d7ee3a3414bf2c79543831bbf29/security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java#L95)):</sup>
Make a constant for this?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/54)

**Comment by mverret** [comment]
:+1:  Looks good

---

Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/54)

**Comment by stustison** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java, line 95 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-platform/54#-JqkSh4LfthpvEDmGWgN)** ([raw file](https://github.com/codice/ddf-platform/blob/80a12ee27b936d7ee3a3414bf2c79543831bbf29/security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java#L95)):</sup>
I decided against a constant and changed it to TimeUnit.MINUTES.toMillis(1) instead. I think it is a little more explicit what it is for that way. Good?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/54)

**Comment by mverret** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java, line 95 \[r2\]](https://reviewable.io:443/reviews/codice/ddf-platform/54#-JqkSh4LfthpvEDmGWgN)** ([raw file](https://github.com/codice/ddf-platform/blob/80a12ee27b936d7ee3a3414bf2c79543831bbf29/security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java#L95)):</sup>
sure

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/54)

**Comment by shaundmorris** [comment]
Did a final build check...

---

Review status: all files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- security/core/security-core-impl/src/main/java/ddf/security/service/impl/SecurityAssertionStore.java @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/54)

**Pull request merged**
