### PR TITLE
DDF-1257 - Resolved merge conflicts with reformatting changes

### PR DESCRIPTION
**Pull request by mverret**
Changed AuthorizationFilter to always pass an ActionPermission to the PDP and fixed a String cast issue in XACMLRealm.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/61)

### CODE REVIEW

**Comment by mverret** [comment]
PR for the ddf repo with the same ticket name is dependent on this PR

**Comment by stustison** [comment]
Did you also test that the Java PDP still works correctly?

**Comment by mverret** [comment]
I ran all of the integration tests including the TestSecurity itest and they all passed.  TestSecurity exercises the Java PDP.

**Comment by garrettfreibott** [comment]
Pulled all changes and it passed checkstyle and itests. :+1:

**Comment by AzGoalie** [comment]
Ran full build with all tests, everything passed.

:+1:

**Comment by shaundmorris** [comment]
Confirmed build and tests with https://github.com/codice/ddf/pull/52

**Pull request merged**
