### PR TITLE
DDF-1296 validators were not setting principal on validate target object which is used for onBehalfOf elements and fixed copy/paste error in metatype for PKI validator

### PR DESCRIPTION
**Pull request by stustison**
@mverret @shaundmorris @clockard

@clockard can hero

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/68)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Looks fairly minor (in terms of lines changed). Is this covered by any existing tests? 

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/68)

**Comment by stustison** [comment]
We do have an integration test for PKI auth, which is the only case where this happened to crop up, but that test doesn't trigger this case. It only seemed to trigger when I was authenticating via REST. Our current test just hits the STS directly. I'll write up a ticket to add integration tests for all of the authentication methods going through REST. Also, I went ahead and added the principal to the other validator's validateTarget objects as well for consistency.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/68)

**Comment by stustison** [comment]
Actually, now that I'm thinking about it, this should have been triggered by Solr since that uses PKI auth through a REST endpoint. That is why we didn't add any test for it in the first place, because it is implicitly being tested. 

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/68)

**Comment by clockard** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/68)

**Comment by shaundmorris** [comment]
Okay thanks. :+1: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/68)

**Comment by clockard** [comment]
Downloaded branch and successfully build and ran all unit/integration tests. 
After configuring DDF for ldap PKI use for the /search context I was unable to successfully load the search ui page. Scott thinks it looks like the same error from before and is looking into the issue.

**Comment by clockard** [comment]
Issue I was having was related to an AdminUI problem and not with this pr. Was able to work around UI issue and verified that it works as expected.
:+1:

**Pull request merged**
