### PR TITLE
DDF-1360 added policy extension interface and updated Java PDP to look for those services

### PR DESCRIPTION
**Pull request by stustison**
@pklinef @mverret @AzGoalie

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/87)

### CODE REVIEW

**Comment by AzGoalie** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/87)

**Comment by ricklarsen** [comment]
Built, ran tests, and verified successful. +1

**Comment by pklinef** [comment]
Do we need to add anything to the integrator's documentation?

**Comment by pklinef** [comment]
We need unit tests to make sure that plugins work and that bad plugins do not break the PDP.

**Pull request merged**
