### PR TITLE
DDF-1182 fixed realm loading in UTValidator

### PR DESCRIPTION
**Pull request by stustison**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/43)

### CODE REVIEW

**Comment by jlcsmith** [comment]
Based on the changes here, I am assuming there were cases where realms were being add/removed after the UTValidator initialization and weren't getting picked up?

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/43)

**Comment by stustison** [comment]
Correct. The UPBSTValidator has these exact same changes, we just neglected to move them over.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/43)

**Comment by jlcsmith** [comment]
This all looks good to me.

**Comment by stustison** [comment]
@pklinef

**Comment by pklinef** [comment]
:+1:

**Pull request merged**
