### PR TITLE
DDF-1270: enabled compiling docs into single html/pdf files.

### PR DESCRIPTION
**Pull request by ricklarsen**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/65)

### CODE REVIEW

**Comment by clockard** [comment]
Reviewed 15 of 16 files at r1.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/65)

**Comment by clockard** [comment]
Reviewed 1 of 16 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/65)

**Comment by clockard** [comment]
:+1:

**Comment by ricklarsen** [comment]
@shaundmorris This PR is ready for review.

**Comment by shaundmorris** [comment]
I built ddf-parent https://github.com/codice/ddf-parent/pull/27. Then ran into an issue: [ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.3.1:install (default-install) on project docs: Failed to install artifact ddf.platform.security:docs:html:DDFOmnibus:2.8.0-SNAPSHOT: ddf/ddf-platform/security/docs/target/docs/html/DDFOmnibus.html (No such file or directory)

**Comment by shaundmorris** [comment]
The build issue was resolved with a fix to ddf-parent under codice/ddf-parent#27

**Pull request merged**
