### PR TITLE
DDF-1341 Removing unnecessary / wrong distribution management in pom

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- Removed distribution management that was overriding the correct configuration from ddf-parent pom.

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/83)

### CODE REVIEW

**Comment by andrew-fiedler** [comment]
@garrettfreibott as hero, @shaundmorris

**Comment by garrettfreibott** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/83)

**Comment by garrettfreibott** [comment]
:+1:  :100:  :8ball:

**Comment by shaundmorris** [comment]
Verified no impacts to build and the clean-up

**Pull request merged**
