### PR TITLE
DDF-1294 added check for https scheme to add cookie method

### PR DESCRIPTION
**Pull request by stustison**
@mverret @djblue @shaundmorris 

@djblue can hero

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/66)

### CODE REVIEW

**Comment by shaundmorris** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java, line 53 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/66#-JsgAG-XIurhoSbRD5x6)** ([raw file](https://github.com/codice/ddf-platform/blob/849fc5fdfed6e273baf85c637026aa007d833c7b/security/common/src/main/java/org/codice/ddf/security/common/jaxrs/RestSecurity.java#L53)):</sup>
Since we are checking for subject to be null I would recommend checking "client" as well.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/66)

**Comment by shaundmorris** [comment]
:+1:  nice null checks

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/66)

**Comment by mverret** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/66)

**Comment by mverret** [comment]
:+1:

**Comment by djblue** [comment]
@stustison I successfully built with your changes. How do I validate the functionality?

**Comment by stustison** [comment]
If you did a non-fast build and everything was successful, then you validated it.

**Comment by djblue** [comment]
Fetched and ran `mvn clean install`. :+1:

**Pull request merged**
