### PR TITLE
DDF-1174 Adding jacoco config to DDF-Platform

### PR DESCRIPTION
**Pull request by andrew-fiedler**
The top pom defers to the DDF-Parent configuration, but the rest of the poms have custom configurations for the minimum code coverage required (determined by an initial run with jacoco, with a subtraction of 5 percent to give some room).

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/38)

### CODE REVIEW

**Comment by lessarderic** [comment]
<sup>**[action/core/platform-action-core-api/pom.xml, line 42 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx5y2zk00yhDC3RQC3)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/action/core/platform-action-core-api/pom.xml#L42)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[compression/platform-compression-gzip/pom.xml, line 40 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx64doiKDzqvOnTJRS)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/compression/platform-compression-gzip/pom.xml#L40)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[docs/pom.xml, line 45 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx68zkxPTj0m74F7E_)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/docs/pom.xml#L45)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[error/platform-error-api/pom.xml, line 47 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6BEqZOkLL4qIkabl)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/error/platform-error-api/pom.xml#L47)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by mrmateo** [comment]
<sup>**[action/core/platform-action-core-api/pom.xml, line 42 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx5y2zk00yhDC3RQC3)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/action/core/platform-action-core-api/pom.xml#L42)):</sup>
Hey Eric, just a friendly FYI - you can do multiple comments and then publish them all at once in reviewable. Might help reduce emails :)

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/cas/security-cas-impl/pom.xml, line 59 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6_BeMNvFt5sMl8vh)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/cas/security-cas-impl/pom.xml#L59)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/docs/pom.xml, line 45 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6d5mPe2qjpERa9fr)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/docs/pom.xml#L45)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/encryption/platform-security-encryption-api/pom.xml, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6f8lHgLYbCnwPHXj)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/encryption/platform-security-encryption-api/pom.xml#L54)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/encryption/platform-security-encryption-commands/pom.xml, line 71 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6hEBp_IaiAFwTdwY)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/encryption/platform-security-encryption-commands/pom.xml#L71)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/encryption/platform-security-encryption-impl/pom.xml, line 60 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6jMmXSr8-IZ5LKnj)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/encryption/platform-security-encryption-impl/pom.xml#L60)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
<sup>**[security/expansion/security-expansion-api/pom.xml, line 54 \[r1\]](https://reviewable.io:443/reviews/codice/ddf-platform/38#-Jnx6rrdn3vT7TTPCckW)** ([raw file](https://github.com/codice/ddf-platform/blob/b3cd9f75d113045722735252611aef3593c24266/security/expansion/security-expansion-api/pom.xml#L54)):</sup>
Uses defaults. Remove.

---


---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
So sorry. Didn't realize you were getting separate emails.

Thanks for letting me know.

Eric

**Comment by lessarderic** [comment]
Andrew, please remove the configuration from all the pom files that use the default values. I did comment on most of them but can't review the last few files (review too big for Reviewable?).

Also make sure none of the pom files override the parent pom's plug-in version. Didn't find any instance of that but since I can't review all the files can't know for sure.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by andrew-fiedler** [comment]
Thanks, I have a script to find the files using the defaults, so I'll use that to find the rest.  

I'll also check to make sure the version isn't being overridden.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by lessarderic** [comment]
Ok, I'll wait until you're done with that and commit the updates before moving on with the code review.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by shaundmorris** [comment]
I pulled this down and got a build failure on security-pep-interceptor: coverage checks have not been met. See log for details. Did I miss something?

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Comment by shaundmorris** [comment]
Okay, I tried using the latest ddf-parent PR on JaCoCo a couple of times and haven't ran into issues so might have to do with some dependencies there.

---









Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/38)

**Pull request merged**
