### PR TITLE
DDF-1264 added new index for case sensitive wildcard searches

### PR DESCRIPTION
**Pull request by wmcnalli**
[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/76)

### CODE REVIEW

**Comment by coyotesqrl** [comment]
:+1:

**Comment by kcwire** [comment]
+1

**Comment by pklinef** [comment]
:+1:

**Comment by emanns95** [comment]
+1

**Comment by coyotesqrl** [comment]
Tested successfully.

**Pull request merged**
