### PR TITLE
DDF-1174 Adding jacoco configuration to DDF-Platform pom files

### PR DESCRIPTION
**Pull request by andrew-fiedler**
- Added jacoco configs to pom files

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/37)

### CODE REVIEW

**Comment by mrmateo** [comment]
I'm not familiar with the JaCoCo maven plugin, but have some questions:

Just from a quick glance it looks like every (or almost every) configuration is the same? Is that something that you can just put once in a parent pom so that all of the children will automatically inherit it or does it need to be in every single pom?

**Comment by andrew-fiedler** [comment]
Yeah, I'm going to be pulling the config into the parent pom, that way we can adjust the levels from .75 to whatever we want in the future.

**Comment by mrmateo** [comment]
OK thanks. So instead of 87 files changed there will just be a couple files changed?

**Comment by andrew-fiedler** [comment]
There will probably still be a large number of file changes, it's just that the top level pom file will defer to the ddf-parent pom.

**Comment by shaundmorris** [comment]
Yeah good call. We should be able to use <pluginManagement> in ddf-parent with the most common config and then only override when necessary.

**Comment by mrmateo** [comment]
Thanks for the answers @andrew-fiedler , I'll give it another look after you pull the configuration into the parent poms.

**Comment by andrew-fiedler** [comment]
Hi @mrmateo , I'm closing this and opening a new pull request (I had accidentally been committing to my master fork, when I should have made a branch for this change).  The new pull request will have the change in configuration.

**Pull request closed without merging**
