### PR TITLE
DDF-1342  Missing .gitignore value from the ddf-solr and ddf-admin merges

### PR DESCRIPTION
**Pull request by coyotesqrl**
Yet another monster.

@pklinef 
@tbatieConnexta 
@jckilmer
@rzwiefel
@roelens8

[Review on Reviewable](https://reviewable.io/reviews/codice/ddf-platform/82)

### CODE REVIEW

**Comment by jckilmer** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/codice/ddf-platform/82)

**Comment by rzwiefel** [comment]
:+1:

**Comment by pklinef** [comment]
Ideally the styles.css file would be generated in the target folder instead of in the src directory.

**Comment by tbatieConnexta** [comment]
:+1:

**Comment by pklinef** [comment]
Write a ticket to not generate the css file in the src directory and mention to remove that line from .gitignore once it is fixed.

:+1:

**Comment by coyotesqrl** [comment]
Did that last night. 😊

**Pull request merged**
